language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2.1-003177
mono:
  - latest
os:
  - linux
node_js:
- '6.10.2'
before_install:
- npm install -g z-schema
- npm install compare-obj diff fs path child_process
install:
- sh script/setup.sh
- sh script/cibuild.sh
- sh script/linters.sh
script:
- node test/integration.js